### ISSUE TITLE
libreoffice 打开失败

### ISSUE THREAD

**Issue by hggq** [totravel/minidocx#1]
想法不错，期待这个minidocx。
测试用例里面生成的docx文件，mac os 自带的pages打开没有问题，但是LibreOffice打开失败

希望有可能表格和图片功能

**Comment by totravel** [comment]
好的，我会看一下是什么问题导致生成的文档不能用 LibreOffice 打开。

另外，minidocx 在不久的未来会支持插入表格和图片。

**Comment by hggq** [comment]
我是在mac os上不行，你可以试下linux 上

**Comment by hggq** [comment]
确实，使用0.2.1 LibreOffice for Mac 可以打开
