### ISSUE TITLE
Separate new method for manage document path

### ISSUE THREAD

**Issue by GermanAizek** [totravel/minidocx#14]
@totravel,
it may be worth adding separate `SetPath(const std::string& path)` method that only sets path from parameter function. Because in my code I made in class private member `docx::Document*`. I have constructor class working on creating an object document, but there is no way to reassigning path.

**Comment by totravel** [comment]
OK. I'm waiting for PR ;)

**Comment by GermanAizek** [comment]
> OK. I'm waiting for PR ;)

Ok

**Comment by totravel** [comment]
Wait. Maybe it shouldn't exist.
