### ISSUE TITLE
如何在qt中使用

### ISSUE THREAD

**Issue by 98-Tiger** [totravel/minidocx#3]
![image](https://user-images.githubusercontent.com/74124101/200999122-6b06d2e6-e439-4aa3-a84d-e6436c8a2ae8.png)
编译出错

**Comment by totravel** [comment]
建议先把 minidocx 编译成一个静态库，构建命令见文档。

**Comment by 98-Tiger** [comment]
![image](https://user-images.githubusercontent.com/74124101/201013794-085247e5-b041-4ed1-a9a3-db4a0cfbafa2.png)
用库还是出错

**Comment by totravel** [comment]
要把 `install/include` 添加到附加包含目录。

**Comment by 98-Tiger** [comment]
这个不能在Windows上用吗

**Comment by totravel** [comment]
minidocx 是跨平台的。在项目中使用 minidocx 的方法与其他第三方库一致。

**Comment by 98-Tiger** [comment]
![image](https://user-images.githubusercontent.com/74124101/201156605-c530a186-5101-4e9e-9052-9a44ac7ab4a7.png)
我把网上的方法试编了就是会出现这个错误，大哥你这个库在Windows上测试过吗
