### ISSUE TITLE
用Table生成的表格，在某些环境下，排版乱了

### ISSUE THREAD

**Issue by loadship** [totravel/minidocx#34]
![116903a55399a3f28592dfd65211dede_compress](https://github.com/user-attachments/assets/65781c12-0cc0-457a-8374-3eca60c76b79)

**Comment by loadship** [comment]
用部分word打开又正常，这什么情况
![image](https://github.com/user-attachments/assets/8988252e-3088-4a0c-bbe4-3efe15700a77)

**Comment by loadship** [comment]
我尝试SetWidth 按A4英寸宽度设置，没有解决
后我又按百分比，设置百分比，还是没有解决

**Comment by loadship** [comment]
实际尝试了下，应该是企业微信没兼容好的问题，测试office、wps都可以正常打开。

**Comment by totravel** [comment]
不排除 minidocx 在某些细节的处理上可能存在问题。其实有很多细节我还没有弄明白。近期可能会发布下一代 minidocx，欢迎保持关注。
