### ISSUE TITLE
添加富文本或段落中的 '\n' 换行无法添加进 Word 文档中

### ISSUE THREAD

**Issue by QtLittleXu** [totravel/minidocx#8]
## 问题描述

使用 AppendParagraph 或 AppendRun 函数向文本中添加的 '\n' 换行无法添加到 Word 文档中，只能调用 AppendLineBreak 函数手动添加换行。

## 期望结果

AppendParagraph 和 AppendRun 函数能够将字符串中的 '\n' 换行添加到 Word 文档中。

## 示例代码

```c++
#include "minidocx.hpp"
using namespace docx;

int main()
{
    Document doc("Test.docx");
    auto p = doc.AppendParagraph("This is first line. \n This is second line.", 16);
    doc.Save();
    return 0;
}
```

## 编译环境

- Windows 环境
  - Windows 11
  - g++ 8.1.0
  - 使用 WPS 阅读 Word
- Linux 环境
  - Linux Mint 21.2
  - g++ 11.4.0
  - 使用 LibreOffice 阅读 Word

## 生成结果

![image](https://github.com/totravel/minidocx/assets/146843108/4fb36f40-3521-4d8d-a2c5-90285379d2b2)

**Comment by totravel** [comment]
应该以段落为单位来组织文档的内容。在 Word 文档中：

- ”行“并不是独立的实体，行的内容不能事先确定，行数也不能事先确定。
- 换行只是特殊的格式。
- 在使用 MS Office 时，按下 Enter 键也是另起一段，而不是另起一行。

**Comment by totravel** [comment]
现在可以在文本中插入 `\n` 和 `\t`。

**Comment by QtLittleXu** [comment]
没想到一年半了这库还在更新呀，我当时提这问题的时候好像才5个issue和20多个star，现在都100多个star了，居然还记得这个问题

**Comment by totravel** [comment]
其实我只是讨厌在原来的代码基础上继续添加新特性，并不是真的觉得你的提议不合理。原来的设计基本上就是没有设计，又包含很多拙劣的代码，所以我一直想推倒重来。
